# Copyright 2026 James Casey
# SPDX-License-Identifier: Apache-2.0

[package]
name = "http"
version = "0.1.0"
description = "HTTP client and server for Beamtalk"

[dependencies]

[native.dependencies]
gun = "~> 2.1"
cowboy = "~> 2.12"
